# Generated by Django 5.2.17 on 2026-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable identifier, e.g. 'LM-PC-0001'. Never reused or renumbered - results reference it.", max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('requirement', models.TextField(help_text='What the package must declare, in plain language a non-lawyer can act on.')),
                ('legal_reference', models.CharField(blank=True, help_text='The provision exactly as the authoritative text numbers it. Blank when not certain - a guessed rule number is worse than none.', max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified against source'), ('unverified', 'Not yet verified')], db_index=True, default='unverified', max_length=16)),
                ('source_note', models.TextField(blank=True, help_text="Who verified this, against what, and when. Required when source_status is 'verified'.")),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='major', max_length=16)),
                ('check_type', models.CharField(db_index=True, help_text='Names a validator registered in apps.rules.checks. Unknown values are rejected at load time.', max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Validator configuration, e.g. {'field_key': 'net_quantity'}. JSON because the shape legitimately differs per check_type; each validator declares and validates its own.")),
                ('effective_from', models.DateField(blank=True, help_text='First date the rule applies.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Last date it applies. Null = in force.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Set False to keep a rule on record without evaluating it.')),
                ('applies_to_categories', models.ManyToManyField(blank=True, help_text='Categories this rule applies to. EMPTY MEANS EVERY COMMODITY - a strong claim, so set it deliberately. Relational rather than JSON because the engine queries applicability by category.', related_name='rules', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active', 'source_status'], name='rule_active_source_idx')],
            },
        ),
    ]
