# Generated by Django 5.2.17 on 2026-09-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicabilityCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable identifier, e.g. 'imported-product'. Referenced by the framework seed files.", max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('determination', models.CharField(choices=[('product_category', 'Derivable from the product category taxonomy'), ('user_declared', 'Would have to be supplied by the submitter; not collected today'), ('database', 'Needs a reference dataset the system does not hold'), ('not_determinable', 'Cannot be established by this system')], db_index=True, default='not_determinable', help_text='Defaults to NOT_DETERMINABLE so a condition added without thought cannot silently license an automatic verdict.', max_length=32)),
                ('determination_note', models.TextField(blank=True, help_text='Why it is or is not determinable, and what would change that.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LegalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation', models.CharField(help_text="The instrument as it cites itself, e.g. 'G.S.R. 128(E)'. Stable - requirements reference it.", max_length=128, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('instrument_type', models.CharField(choices=[('principal', 'Principal rules'), ('amendment', 'Amending notification'), ('consolidated_publication', 'Departmental consolidated publication')], db_index=True, default='amendment', max_length=32)),
                ('notified_on', models.DateField(blank=True, help_text='Date of the notification itself. Distinct from when it comes into force: for G.S.R. 312(E) the two are fourteen months apart, and conflating them would date a requirement wrong by that much.', null=True)),
                ('effective_from', models.DateField(blank=True, help_text='Date the instrument comes into force. Null when the source consulted does not establish one - never guessed.', null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_sha256', models.CharField(blank=True, help_text='Digest of the exact document that was read, so a later reviewer can confirm they hold the same bytes.', max_length=64)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified against source'), ('unverified', 'Not yet verified'), ('requires_review', 'Requires human review')], db_index=True, default='unverified', max_length=16)),
                ('verification_note', models.TextField(blank=True, help_text="Who read this, when, and what they could NOT establish. Required when verification_status is 'verified'.")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['notified_on', 'citation'],
            },
        ),
        migrations.CreateModel(
            name='LegalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_number', models.CharField(help_text="As the Rules number it: '6', '32A'. A string rather than an integer, because rule 32-A exists.", max_length=8, unique=True)),
                ('sort_key', models.CharField(db_index=True, help_text="Zero-padded number plus any suffix ('006', '032A'), so rule 32-A sorts between 32 and 33 and rule 10 does not sort before rule 2. Derived by the loader, never authored.", max_length=8)),
                ('chapter', models.CharField(blank=True, help_text="Chapter of the Rules, e.g. 'Chapter II - Packages intended for retail sale'.", max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='What the rule covers, in plain language. Never a substitute for the verbatim text held on each requirement.')),
                ('automation_class', models.CharField(choices=[('image_automatable', 'Decidable from a label photograph'), ('partially_automatable', 'Partly decidable; some element needs input the image does not carry'), ('digital_ecommerce', 'Concerns an online listing rather than the package'), ('physical_measurement', 'Needs weighing, measuring or physical sampling'), ('administrative', "Needs a regulator's administrative record"), ('manual_review', 'Needs human legal judgement and must not be automated')], db_index=True, help_text='Headline classification for the rule as a whole. Individual requirements may differ, and theirs governs.', max_length=32)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified against source'), ('unverified', 'Not yet verified'), ('requires_review', 'Requires human review')], db_index=True, default='unverified', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sort_key'],
            },
        ),
        migrations.CreateModel(
            name='RequirementApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('requires', 'Applies only when this condition holds'), ('exempts', 'Does not apply when this condition holds'), ('scope_gate', 'Removes the package from scope entirely')], db_index=True, max_length=16)),
                ('note', models.TextField(blank=True, help_text='The proviso or explanation this link comes from, quoted or cited.')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_links', to='rules.applicabilitycondition')),
            ],
            options={
                'verbose_name_plural': 'requirement applicability',
                'ordering': ['requirement_id', 'condition_id'],
            },
        ),
        migrations.CreateModel(
            name='RuleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause', models.CharField(db_index=True, help_text="Sub-rule or clause as the Rules number it: '6(1)(c)', '6(10A)', '9(1)(a)'. The bare rule number when the whole rule is the unit.", max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Increments per amendment of this clause. Version 1 is the earliest text this framework records, which is not necessarily the clause as first enacted.')),
                ('title', models.CharField(max_length=255)),
                ('requirement', models.TextField(help_text='What is required, in plain language a non-lawyer can act on.')),
                ('verbatim_text', models.TextField(blank=True, help_text='The clause quoted from the source. Blank when nobody has transcribed it - never filled from paraphrase or memory.')),
                ('detection_method', models.CharField(choices=[('ocr', 'OCR - text read from the label'), ('cv', 'Computer vision - a rendered or geometric property'), ('ocr_cv', 'OCR and computer vision together'), ('database', 'Lookup against a reference dataset'), ('user_input', 'Supplied by the submitter, not read from the image'), ('digital_ecommerce', 'The e-commerce listing, not the physical package'), ('physical_inspection', 'Physical handling, weighing or measurement of the package'), ('administrative', 'An administrative or registration record held by a regulator'), ('manual_review', 'Human legal judgement'), ('not_applicable', 'Not an obligation this system assesses at all')], db_index=True, help_text='What evidence could settle this requirement. Anything outside DetectionMethod.image_evaluable() cannot be decided from a photograph.', max_length=32)),
                ('automation_class', models.CharField(choices=[('image_automatable', 'Decidable from a label photograph'), ('partially_automatable', 'Partly decidable; some element needs input the image does not carry'), ('digital_ecommerce', 'Concerns an online listing rather than the package'), ('physical_measurement', 'Needs weighing, measuring or physical sampling'), ('administrative', "Needs a regulator's administrative record"), ('manual_review', 'Needs human legal judgement and must not be automated')], db_index=True, max_length=32)),
                ('implementation_status', models.CharField(choices=[('implemented', 'Implemented and evaluated'), ('implementable_now', 'Implementable with existing machinery'), ('implementable_with_new_check', 'Needs a check type that does not exist'), ('blocked_by_missing_applicability_data', 'The system does not collect the fact that decides whether it applies'), ('blocked_by_missing_extraction_field', "The declaration is not in the extractor's supported set"), ('legal_review_required', 'Wording or applicability needs a qualified human first'), ('not_applicable_to_project_scope', 'A real obligation, but not one a label checker can assess')], db_index=True, help_text='What stands between this requirement and evaluation today.', max_length=48)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='major', help_text="Triage ranking, sharing ComplianceRule's vocabulary. Carries no legal weight of its own.", max_length=16)),
                ('legal_reference', models.CharField(blank=True, help_text="Citable form, e.g. 'Rule 6(1)(c) of the Legal Metrology (Packaged Commodities) Rules, 2011'.", max_length=255)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified against source'), ('unverified', 'Not yet verified'), ('requires_review', 'Requires human review')], db_index=True, default='unverified', max_length=16)),
                ('source_note', models.TextField(blank=True, help_text="Who checked this against what, and anything the source did NOT settle. Required when verification_status is 'verified'.")),
                ('effective_from', models.DateField(blank=True, help_text='First date this version applies. Null when the source consulted does not establish one.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text="Last date it applies. Null means still in force - or, when verification_status is 'requires_review', that the source did not settle when it stops. The two are told apart by source_note, never by inventing a date.", null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False keeps a requirement on record without treating it as part of the present framework - rule 5, omitted, is the case this exists for.')),
                ('applicability_conditions', models.ManyToManyField(blank=True, related_name='requirements', through='rules.RequirementApplicability', to='rules.applicabilitycondition')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='rules.legalrule')),
                ('source', models.ForeignKey(blank=True, help_text='The instrument that established this version of the clause.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='rules.legalinstrument')),
                ('supersedes', models.ForeignKey(blank=True, help_text='The version this one replaces. PROTECT: deleting an earlier version would orphan the history that explains this one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='rules.rulerequirement')),
            ],
            options={
                'ordering': ['rule__sort_key', 'clause', 'version'],
            },
        ),
        migrations.AddField(
            model_name='requirementapplicability',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_links', to='rules.rulerequirement'),
        ),
        migrations.AddField(
            model_name='compliancerule',
            name='rule_requirement',
            field=models.ForeignKey(blank=True, help_text='The clause-level legal requirement this executable rule evaluates. The single link between the executable layer and the legal framework below. Nullable, and its absence is not an oversight: a rule may be drafted before the clause it implements has been transcribed and verified. PROTECT, so a requirement that rules and findings cite cannot be deleted out from under them. A requirement may have several rules - presence and format are separate checks of one clause - so the key sits here, not there.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_rules', to='rules.rulerequirement'),
        ),
        migrations.AddIndex(
            model_name='rulerequirement',
            index=models.Index(fields=['implementation_status', 'automation_class'], name='requirement_status_auto_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulerequirement',
            constraint=models.UniqueConstraint(fields=('clause', 'version'), name='requirement_clause_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='requirementapplicability',
            constraint=models.UniqueConstraint(fields=('requirement', 'condition', 'mode'), name='requirement_condition_mode_uniq'),
        ),
    ]
