# Generated by Django 5.2.17 on 2026-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_applicabilitycondition_legalinstrument_legalrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementapplicability',
            name='mode',
            field=models.CharField(choices=[('requires', 'Applies only when this condition holds'), ('exempts', 'Does not apply when this condition holds'), ('scope_gate', 'Removes the package from scope entirely'), ('withholds_exemption', 'Cancels an exemption, so the Rules continue to apply')], db_index=True, max_length=24),
        ),
    ]
