# Generated by Django 5.2.17 on 2026-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_requirementapplicability_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicabilitycondition',
            name='category_code',
            field=models.SlugField(blank=True, help_text="For a PRODUCT_CATEGORY condition, the `ProductCategory.code` whose ancestry answers it: a product in 'packaged-food', or any descendant of it, holds the 'food-article' condition. Blank for every other determination, and required for this one - without it PRODUCT_CATEGORY would be a label with nothing behind it, and the resolver would report the fact unknown for a product whose category already settles it.", max_length=64),
        ),
    ]
