# Generated by Django 5.2.17 on 2026-09-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_applicabilitycondition_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerule',
            name='requires_applicability_conditions',
            field=models.BooleanField(default=False, help_text="True when this rule is only safe to evaluate once its clause's applicability conditions have been resolved - i.e. it was unblocked BY applicability rather than despite it.\n\nThe failure this prevents: rule 6(1)(aa) binds imported packages only. With the legal framework not loaded, `rule_requirement` is null, no trigger condition is found, and the rule would apply to every package - failing every domestic one for want of a country of origin it never had to declare. That is the same shape of bug as LM-PC-0002, which reported a violation against every product.\n\nSo the engine records INCONCLUSIVE rather than evaluating such a rule unmapped. Set it for any rule whose activation depended on a trigger or an exemption."),
        ),
    ]
