# Generated by Django 5.2.17 on 2026-08-25 14:52

import apps.images.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(help_text='Stored under a generated name; see apps.images.storage.', max_length=255, upload_to=apps.images.storage.product_image_upload_path)),
                ('original_filename', models.CharField(help_text='Sanitised client-supplied name, for display only. Never used to build a filesystem path.', max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('image_format', models.CharField(help_text='Canonical format as decoded (jpeg/png/webp), not as claimed.', max_length=16)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, help_text='SHA-256 of the uploaded bytes. Ties a compliance result to the exact file analysed, and makes tampering detectable.', max_length=64)),
                ('view_type', models.CharField(choices=[('unspecified', 'Unspecified'), ('front', 'Front panel'), ('back', 'Back panel'), ('principal_display', 'Principal display panel'), ('label', 'Label close-up'), ('other', 'Other')], default='unspecified', max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=16)),
                ('product', models.ForeignKey(blank=True, help_text='Null until the product is identified. CASCADE: deleting a product removes its images and their analyses.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'view_type'], name='image_product_view_idx')],
            },
        ),
    ]
