# Generated by Django 5.2.17 on 2026-08-25 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable identifier referenced by rule definition files, e.g. 'packaged-food'. Do not rename after rules reference it.", max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent category. PROTECT rather than CASCADE: deleting a parent must not silently remove the sub-categories that rules and products point at.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.productcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Working name for this submission. Not a label declaration.', max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='EAN/UPC if known. Not unique: the same article may be submitted more than once, and barcodes are re-used.', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null once the creating user is deleted; the product and its compliance history are retained.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text="Determines which rules apply. Null means the category is not yet known, which the compliance engine treats as 'cannot determine applicability' rather than 'no rules apply'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='product_created_idx')],
            },
        ),
    ]
