# Generated by Django 5.2.17 on 2026-09-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('rules', '0003_alter_requirementapplicability_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplicabilityDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Not known')], db_index=True, default='unknown', help_text='Defaults to UNKNOWN so a row created without an answer cannot assert one.', max_length=8)),
                ('source', models.CharField(choices=[('submitter', 'Declared by the submitter'), ('reviewer', 'Recorded by a reviewer'), ('category', 'Derived from the product category')], default='submitter', max_length=16)),
                ('note', models.TextField(blank=True, help_text='Why this was answered as it was. Shown to a reviewer beside any finding the answer influenced.')),
                ('condition', models.ForeignKey(help_text='PROTECT: a condition that submissions have answered must not be deletable, or their answers lose their meaning.', on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='rules.applicabilitycondition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_declarations', to='catalog.product')),
            ],
            options={
                'ordering': ['condition__code'],
                'constraints': [models.UniqueConstraint(fields=('product', 'condition'), name='product_condition_declaration_uniq')],
            },
        ),
    ]
