# Generated by Django 5.2.17 on 2026-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productapplicabilitydeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_basis',
            field=models.TextField(blank=True, help_text='Why the category is what it is, when it was not simply stated: the classifier, its version, its confidence and the policy entry that accepted it. Blank when a person stated the category.'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_source',
            field=models.CharField(choices=[('submitter', 'Stated by the submitter'), ('reviewer', 'Recorded by a reviewer'), ('classifier', 'Established automatically from the label classifier')], default='submitter', help_text='Who or what set `category`. Defaults to the submitter, which is what every row written before this field existed was.', max_length=16),
        ),
    ]
