# Generated by Django 5.2.17 on 2026-09-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(editable=False, help_text='SHA-256 of the token, hex. The token itself is not stored.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Set at issue from API_TOKEN_LIFETIME_HOURS. Not extended by use.')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the token was revoked, by logout or by an operator. Null while it has not been.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Approximate: refreshed at most every few minutes, so authenticating does not write to the database on every request.', null=True)),
                ('user', models.ForeignKey(help_text='A token has no meaning without its user, so it goes with them.', on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
