"""Turning an uploaded file into a stored `ProductImage`.

`validators.validate_image_upload` decides whether a file is acceptable and
measures what it actually is. This module is the other half: it takes those
measured facts and writes the row. Keeping them apart matters because the
validator is pure - it can be exercised with no database - while this needs
one.

Why a service rather than a serializer
--------------------------------------
There is no image API endpoint yet (see `docs/api.md`, "Planned endpoints").
Until there is, a management command, a test, and a future DRF view all need
the same sequence: validate, then persist exactly what validation measured.
Writing that sequence in a view would mean the other two callers either
duplicate it or skip validation - and skipping it is the one failure mode this
whole layer exists to prevent.

What it deliberately does not do
--------------------------------
It does not run extraction. Ingestion succeeding means "these bytes are a real
image and we have kept them"; it makes no claim about whether anything is
legible on them. `apps.extraction.services.extraction_service` answers that,
against a row this module has already committed.
"""

from __future__ import annotations

import logging

from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import UploadedFile

from apps.images.models import ProductImage
from apps.images.validators import ValidatedImage, validate_image_upload

logger = logging.getLogger(__name__)


def ingest_product_image(
    upload: UploadedFile,
    *,
    product=None,
    uploaded_by=None,
    view_type: str = ProductImage.ViewType.UNSPECIFIED,
) -> ProductImage:
    """Validate `upload` and store it as a `ProductImage`.

    Every measured column on the returned row comes from `ValidatedImage` -
    that is, from the bytes - and none of it from the upload's own claims about
    itself. The stored filename is generated by
    `storage.product_image_upload_path`; `original_filename` keeps the
    sanitised client name for display only and never reaches a path.

    Args:
        upload: The file as received. Consumed and rewound by validation.
        product: The commodity this photograph shows, when it is already known.
            Left null otherwise - the workflow is upload-then-identify.
        uploaded_by: The user, when the request is authenticated.
        view_type: Which panel of the package the photograph shows. Checked
            against `ProductImage.ViewType`, because the column stores choices
            without enforcing them and an unrecognised value would silently
            mislead the compliance engine about what the photo can be expected
            to show.

    Returns:
        The saved `ProductImage`. Its file exists in storage.

    Raises:
        ValidationError: the upload is not an acceptable product image, or
            `view_type` is not a recognised value. Both carry a `code`, so a
            DRF view surfaces them through the standard error envelope as a
            400 rather than a 500.
    """
    if upload is None:
        raise ValidationError("No file was supplied.", code="no_file")

    view_type = _validated_view_type(view_type)

    # Runs first and unconditionally. Nothing below may be reached by a caller
    # that wants to "just store this file" - there is no such entry point.
    facts: ValidatedImage = validate_image_upload(upload)

    image = ProductImage.objects.create(
        product=product,
        uploaded_by=uploaded_by,
        image=upload,
        original_filename=facts.original_filename,
        content_type=facts.content_type,
        image_format=facts.image_format,
        size_bytes=facts.size_bytes,
        width=facts.width,
        height=facts.height,
        checksum_sha256=facts.checksum_sha256,
        view_type=view_type,
        status=ProductImage.Status.UPLOADED,
    )

    # The stored name, not the client's: logging the latter would let an
    # uploader write chosen text into our logs.
    logger.info(
        "Stored product image %s (%s, %d bytes) at %s",
        image.pk,
        facts.image_format,
        facts.size_bytes,
        image.image.name,
    )
    return image


def _validated_view_type(view_type: str) -> str:
    if view_type not in ProductImage.ViewType.values:
        allowed = ", ".join(ProductImage.ViewType.values)
        raise ValidationError(
            f"Unknown view type. Allowed values: {allowed}.",
            code="unknown_view_type",
        )
    return view_type
