# Generated by Django 5.2.17 on 2026-08-25 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_name', models.CharField(help_text='Pipeline name as resolved from the labelextract registry.', max_length=64)),
                ('engine_version', models.CharField(max_length=32)),
                ('is_placeholder', models.BooleanField(default=False, help_text='True when this run came from a placeholder engine that performs no real recognition. Surfaced through the API so the UI can never present wiring output as a genuine reading.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('empty', 'Empty'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, help_text='Wall-clock time inside the extraction pipeline.', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Stable code from labelextract.exceptions when status is failed. The frontend branches on this, not on the message.', max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, default=dict, help_text='Verbatim engine diagnostics. Shape is engine-specific and is deliberately not modelled. Kept so field extraction can be re-run without re-running OCR.')),
                ('recognised_text', models.TextField(blank=True, help_text='All recognised text, joined. Stored for display and search; the authoritative per-block data lives in raw_output.')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='images.productimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedLabelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(db_index=True, help_text='A labelextract.contracts.LabelFieldKey value. Choices are not enumerated at the database level on purpose: the vocabulary is owned by the ml/ package, and duplicating it here would create two lists to keep in sync. Validated in the service layer.', max_length=64)),
                ('raw_value', models.TextField(help_text='Text exactly as recognised. Never cleaned in place, so the original reading stays auditable.')),
                ('normalized_value', models.JSONField(blank=True, help_text="Structured interpretation, e.g. {'quantity': 500, 'unit': 'g'}. Null when no normaliser exists for this key yet. JSON because the shape differs per field type.", null=True)),
                ('confidence', models.FloatField(blank=True, help_text="Engine confidence in [0, 1], or NULL when the engine does not report one. NULL means 'unknown' and must never be treated as zero or as certainty.", null=True)),
                ('bounding_box', models.JSONField(blank=True, help_text="{'x','y','width','height'} in source-image pixels, or null. Lets the UI show where on the package this was read.", null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='extraction.extractionrun')),
            ],
            options={
                'ordering': ['field_key'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['image', '-created_at'], name='run_image_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlabelfield',
            index=models.Index(fields=['run', 'field_key'], name='field_run_key_idx'),
        ),
    ]
