# Generated by Django 5.2.17 on 2026-08-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadLabelDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(db_index=True, help_text="A labelextract.contracts.LabelFieldKey value, validated in the service layer against the ml/ package's vocabulary - the same guard ExtractedLabelField.field_key gets, for the same reason.", max_length=64)),
                ('evidence_text', models.TextField(help_text='The recognised line the keyword was found on, exactly as read. Never blank: an observation nobody can check is an unfalsifiable claim, so a row without it is refused at the service boundary.')),
                ('confidence', models.FloatField(blank=True, help_text="Engine confidence in the evidence line, in [0, 1], or NULL when the engine reported none. NULL means 'unknown' and must never be read as zero.", null=True)),
                ('bounding_box', models.JSONField(blank=True, help_text="{'x','y','width','height'} in source-image pixels, or null. Lets the UI point a reviewer at the panel to re-photograph.", null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_declarations', to='extraction.extractionrun')),
            ],
            options={
                'ordering': ['field_key'],
                'indexes': [models.Index(fields=['run', 'field_key'], name='unread_run_key_idx')],
            },
        ),
    ]
