# Generated by Django 5.2.17 on 2026-09-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRunImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text="1-based place of this photograph in the set, as the submitter supplied it. Position 1 is the run's primary image. Stored, not derived: it is the number the interface shows beside a piece of evidence.")),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('empty', 'Empty'), ('failed', 'Failed')], default='completed', help_text='What the pipeline made of this photograph on its own.', max_length=16)),
                ('error_code', models.CharField(blank=True, help_text='Stable code from labelextract.exceptions when this photograph failed, even though others in the set may have been read.', max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, help_text='Wall-clock time the pipeline spent on this photograph.', null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='extractedlabelfield',
            name='image',
            field=models.ForeignKey(blank=True, help_text='The photograph this declaration was read from. The link that lets a finding say which image supplied its evidence, rather than only that the package showed it somewhere.\n\nNull means the source was not recorded - every reading made before a run could hold more than one photograph, and any reading whose image row has since been deleted. Null is never a claim that no image was involved, and a client must not present it as one.\n\nSET_NULL rather than CASCADE: deleting an image must not delete the reading that was made from it, because findings snapshot that reading and would lose their evidence with it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_fields', to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='extractionrun',
            name='image',
            field=models.ForeignKey(help_text="The primary photograph - position 1 of this run's image set. Not the only one: see ExtractionRunImage. Kept as a direct foreign key so that every query, index and serializer written before a run could read more than one photograph still resolves.", on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='images.productimage'),
        ),
        migrations.AddIndex(
            model_name='extractedlabelfield',
            index=models.Index(fields=['run', 'image'], name='field_run_image_idx'),
        ),
        migrations.AddField(
            model_name='extractionrunimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_memberships', to='images.productimage'),
        ),
        migrations.AddField(
            model_name='extractionrunimage',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_images', to='extraction.extractionrun'),
        ),
        migrations.AddConstraint(
            model_name='extractionrunimage',
            constraint=models.UniqueConstraint(fields=('run', 'position'), name='run_image_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='extractionrunimage',
            constraint=models.UniqueConstraint(fields=('run', 'image'), name='run_image_member_unique'),
        ),
    ]
