# Generated by Django 5.2.17 on 2026-08-25 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('extraction', '0001_initial'),
        ('images', '0001_initial'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('result', models.CharField(choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially compliant'), ('non_compliant', 'Non-compliant'), ('review_required', 'Review required')], db_index=True, default='review_required', help_text='Defaults to REVIEW_REQUIRED so an incomplete check can never read as a clean bill of health.', max_length=32)),
                ('engine_version', models.CharField(help_text='Version of the compliance engine that produced this result, so a verdict stays interpretable after the engine changes.', max_length=32)),
                ('rules_evaluated', models.PositiveIntegerField(default=0, help_text='Applicable rules that were actually evaluated.')),
                ('rules_passed', models.PositiveIntegerField(default=0)),
                ('rules_failed', models.PositiveIntegerField(default=0)),
                ('rules_inconclusive', models.PositiveIntegerField(default=0, help_text='Rules that could not be decided, usually because the image was not readable.')),
                ('summary', models.TextField(blank=True, help_text='Plain-language explanation of how this result was reached, including what could NOT be determined.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_run', models.ForeignKey(help_text='The readings this check was evaluated against.', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='extraction.extractionrun')),
                ('product', models.ForeignKey(blank=True, help_text='Null when the image has not been linked to a product yet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='catalog.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(help_text='Copied from the rule at evaluation time. Not redundant: rules are amended, and past findings must not silently change meaning.', max_length=16)),
                ('rule_code', models.CharField(db_index=True, max_length=64)),
                ('legal_reference', models.CharField(blank=True, max_length=255)),
                ('field_key', models.CharField(blank=True, help_text='The label declaration this finding concerns, if any.', max_length=64)),
                ('message', models.TextField(help_text='What was observed and why it was flagged, in plain language.')),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='compliance.compliancecheck')),
                ('rule', models.ForeignKey(help_text='PROTECT: a rule with recorded findings must not be deletable, or the findings lose their justification.', on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='rules.compliancerule')),
            ],
            options={
                'ordering': ['rule_code'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True, help_text='The recognised text supporting the finding. For an absent declaration, what WAS read instead.')),
                ('bounding_box', models.JSONField(blank=True, help_text="{'x','y','width','height'} in source-image pixels, so the UI can highlight the region. Null when not localised.", null=True)),
                ('note', models.TextField(blank=True)),
                ('extracted_field', models.ForeignKey(blank=True, help_text='The specific reading, when the evidence is a declaration that WAS found. Null when the evidence is an absence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='extraction.extractedlabelfield')),
                ('image', models.ForeignKey(blank=True, help_text='The image this was read from, so the UI can show it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='images.productimage')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='compliance.complianceviolation')),
            ],
            options={
                'verbose_name_plural': 'compliance evidence',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['product', '-created_at'], name='check_product_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['result'], name='check_result_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceviolation',
            index=models.Index(fields=['compliance_check', 'severity'], name='violation_check_sev_idx'),
        ),
    ]
