# Generated by Django 5.2.17 on 2026-08-31 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('extraction', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('inconclusive', 'Inconclusive')], db_index=True, help_text='What the registered validator concluded.', max_length=16)),
                ('downgraded_from_failed', models.BooleanField(default=False, help_text='True when the validator returned FAILED but the rule is not verified against the authoritative legal text, so the engine recorded it as inconclusive instead. Surfaced because the downgrade is a deliberate legal safeguard, and a reviewer needs to see that it happened rather than infer it.')),
                ('rule_code', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('requirement', models.TextField(blank=True, help_text="What the package must declare, in the rule's own words. Snapshotted so a finding stays readable on its own - this is the 'expected requirement' half of the finding, and without it a rule code means nothing to a user.")),
                ('legal_reference', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(help_text='Triage ranking copied from the rule. Carries no legal weight - see rules/SCHEMA.md.', max_length=16)),
                ('check_type', models.CharField(blank=True, help_text='Which registered validator produced this outcome.', max_length=32)),
                ('field_key', models.CharField(blank=True, db_index=True, help_text='The label declaration this outcome concerns, if any.', max_length=64)),
                ('extracted_confidence', models.FloatField(blank=True, help_text="The OCR/ML confidence for the reading behind this finding, in [0, 1], or NULL when the engine did not report one or the finding is about an absence. NULL means 'unknown' and must never be read as zero or as certainty. Snapshotted rather than followed through `extracted_field` so it survives the reading being deleted. Recorded, not thresholded: no rule in this repository conditions its outcome on it.", null=True)),
                ('message', models.TextField(help_text='What was observed and why, in plain language. Written by the validator, copied verbatim.')),
                ('evidence_excerpt', models.TextField(blank=True, help_text='Text read from the label supporting this outcome. For an absence, what WAS read instead.')),
                ('bounding_box', models.JSONField(blank=True, help_text="{'x','y','width','height'} in source-image pixels, or null.", null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Validator diagnostics, verbatim from CheckOutcome.details. Shape is validator-specific and deliberately not modelled.')),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='compliance.compliancecheck')),
                ('extracted_field', models.ForeignKey(blank=True, help_text='The specific reading this outcome was drawn from, when the declaration was found. Null when the finding is about an absence. This is the link that makes a finding traceable back to the pixels it came from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='extraction.extractedlabelfield')),
                ('rule', models.ForeignKey(help_text='PROTECT, for the same reason as on ComplianceViolation: a rule with recorded outcomes must not be deletable.', on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='rules.compliancerule')),
                ('violation', models.OneToOneField(blank=True, help_text='The violation this finding was recorded as, when it failed and the rule was verified. Null for a pass, for an inconclusive outcome, and for a failure that was downgraded because the rule is unverified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding', to='compliance.complianceviolation')),
            ],
            options={
                'ordering': ['rule_code'],
                'indexes': [models.Index(fields=['compliance_check', 'status'], name='finding_check_status_idx')],
            },
        ),
    ]
