# Generated by Django 5.2.17 on 2026-09-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_compliance_finding'),
        ('rules', '0002_applicabilitycondition_legalinstrument_legalrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancefinding',
            name='applicability_note',
            field=models.TextField(blank=True, help_text='Why this requirement was treated as applicable, and - more importantly - what about its applicability could NOT be established. Rule 3 and rule 26 take packages out of scope on facts this system does not collect, so an active rule is applied to some packages that are outside the Rules entirely. This is where that caveat is recorded against the individual finding rather than left in a document.'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='clause',
            field=models.CharField(blank=True, db_index=True, help_text="The sub-rule or clause this outcome concerns, as the Rules number it: '6(1)(c)'. Snapshotted separately from `legal_reference` because a reviewer filters and groups by clause, and parsing it back out of a citation string is exactly the kind of guess this schema exists to avoid.", max_length=32),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='detection_method',
            field=models.CharField(blank=True, help_text="How this requirement is capable of being evaluated at all, copied from the linked requirement. Blank when the rule is not mapped to the framework. It is the field that says whether a photograph could ever have settled this - a finding whose method is 'physical_inspection' or 'administrative' is a review prompt, not a verdict, however it reads. See rules.DetectionMethod.", max_length=32),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='extracted_normalized_value',
            field=models.JSONField(blank=True, help_text='The normalised form of the reading, when a normaliser exists for the field. Null means no normaliser ran - never that the value was empty, and never that the raw text was unparseable. JSON because the normalised shape differs per declaration: a quantity has a magnitude and a unit, a date has a month and a year.', null=True),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='extracted_raw_value',
            field=models.TextField(blank=True, help_text='The declaration exactly as it was recognised, before any normalisation. Snapshotted here as well as on the reading itself because `extracted_field` is SET_NULL: deleting a run must not leave a finding whose evidence has silently become empty. Kept alongside `extracted_normalized_value` and never replaced by it - normalisation is an interpretation, and the original text is what a reviewer needs to check that interpretation against.'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='legal_source_citation',
            field=models.CharField(blank=True, help_text="The instrument that established the requirement as evaluated, e.g. 'G.S.R. 629(E)'. Snapshotted, not followed through the foreign key: which amendment a finding rested on must stay legible after a later amendment supersedes it.", max_length=128),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='rule_requirement',
            field=models.ForeignKey(blank=True, help_text='The clause-level legal requirement behind this outcome, when the evaluated rule is linked to one. Null for a rule that has not been mapped to the framework yet - which is a gap in the mapping, never a statement that no legal basis exists. PROTECT for the same reason as `rule`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='rules.rulerequirement'),
        ),
    ]
