# Generated by Django 5.2.17 on 2026-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancefinding_applicability_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='rules_not_applicable',
            field=models.PositiveIntegerField(default=0, help_text="Rules selected for this product's category that applicability then ruled out - an exemption under rule 26, a scope gate under rule 3, or a clause that binds only packages of a kind this one is not. Counted separately from `rules_evaluated` because an exemption is not evidence of compliance: a package every rule excused has had nothing checked, and must reach REVIEW_REQUIRED."),
        ),
        migrations.AlterField(
            model_name='compliancefinding',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('inconclusive', 'Inconclusive'), ('not_applicable', 'Not applicable')], db_index=True, help_text='What the registered validator concluded.', max_length=16),
        ),
    ]
